---
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 labctl
        language: python
        pass_filenames: false
      - id: black
        name: black
        entry: black --check .
        language: python
        pass_filenames: false
      - id: pyre
        name: pyre
        entry: pyre
        language: python
        pass_filenames: false
      - id: tests
        name: tests
        entry: green
        language: python
        pass_filenames: false
