---
dist: bionic

language: python
python: "3.8"

cache:
  pip: true

before_install:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - export PIPENV_VENV_IN_PROJECT=1

install:
  - pip install -Iv pipenv==2020.6.2
  - pipenv install -d

script:
  - pipenv run pyre --noninteractive
  - pipenv run green --run-coverage

after_success:
  - pip install codecov
  - codecov
