---
dist: bionic

language: python
python:
  - "3.7"
  - "3.8"

jobs:
  allow_failures:
    - python: "3.7"

cache:
  pip: true

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - sed -i "s#.venv#$(poetry env info --path)#g" .pyre_configuration

script:
  - poetry run flake8
  - poetry run black --check .
  - poetry run pyre --noninteractive
  - poetry run green --run-coverage

after_success:
  - pip install codecov
  - codecov
