---
dist: bionic

language: python
python:
  - "3.7"
  - "3.8"

cache:
  pip: true

before_install:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - export PIPENV_VENV_IN_PROJECT=1

install:
  - pip install -Iv pipenv==2020.8.13
  - pipenv install -d

script:
  - pipenv run flake8
  - pipenv run black --check .
  - pipenv run pyre --noninteractive
  - pipenv run green --run-coverage

after_success:
  - pip install codecov
  - codecov
